# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano@2.0.0" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano@2.0.0
#     shield: reviung41
#
---
include:
  # - board: nice_nano@2.0.0
  #   shield: settings_reset

  - board: nice_nano@2.0.0
    shield: donki36_dongle
    # snippet: studio-rpc-usb-uart

  - board: xiao_ble
    shield: donki36_donglx
    # snippet: studio-rpc-usb-uart

  - board: nice_nano@2.0.0
    shield: donki36_left

  - board: nice_nano@2.0.0
    shield: donki36_right

  - board: xiao_ble
    shield: donki36_tball0

  - board: xiao_ble
    shield: donki36_tball1

  - board: xiao_ble
    shield: donki36_tball2

  - board: xiao_ble
    shield: donki36_tpoint0

  # - board: xiao_ble
  #   shield: donki36_tpad0

  - board: xiao_ble
    shield: donki36_mou0

  - board: xiao_ble
    shield: donki36_mou1

  - board: xiao_ble
    shield: donki36_mou2
