file_format: "1"
id: corne36
name: corne36
type: shield
url: https://github.com/badjeff/corne36/
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - corne36_left
  - corne36_right
  - corne36_tball0
  - corne36_tball1
  - corne36_tball2
  - corne36_tpoint0
  - corne36_tpad0
  - corne36_mou0
  - corne36_mou1
  - corne36_dongle
  - corne36_dongleft
