identifier: nologo_nano33_ble
name: Nologo NANA33 BLE
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - ble
  - i2c
  - pwm
  - serial
  - spi
  - uart
  - usb_cdc
  - usb_device
  - watchdog
vendor: nologo
